#!/bin/bash

SUBCMD="$1"
shift

source "$HOME/bin/sqlvm/version.sh"
if [[ "$SUBCMD" == "--version" ]]; then
  echo "$SQLVM_VERSION"
  exit 0
fi

PWD=$(pwd)
SCRIPT_PATH="$PWD/scripts/${SUBCMD}.sh"

if [[ -f "$SCRIPT_PATH" ]]; then
  bash "$SCRIPT_PATH" "$@"
else
  bash "$PWD/scripts/help.sh" "$SUBCMD"
fi
